# Generated by Django 3.1.2 on 2022-09-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20220925_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measurements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.measurement'),
        ),
    ]
