# Generated by Django 3.1.2 on 2022-09-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_auto_20220925_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.sensor', verbose_name='Датчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
